CyberHex/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_accounts.urls')),
    path('', include('discussion_forum.urls')),
    path('messages/', include('private_messages.urls')),
    path('interactions/', include('post_interactions.urls')),
    path('notifications/', include('notifications.urls')),
]

discussion_forum/urls.py
from django.urls import path
from . import views

app_name = 'discussion_forum'

urlpatterns = [
    path('', views.forum_index, name='forum_index'),
    path('topic/<str:topic_title>/', views.topic_detail, name='topic_detail'),
    path('category/<int:category_id>/', views.category_topics, name='category_topics'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
]

user_accounts/urls.py
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'user_accounts'

urlpatterns = [
    path('', views.accounts_index, name='accounts_index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('logout/', views.custom_logout, name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
]

CyberHex/views.py
from django.shortcuts import render

CyberHex/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>CyberHex</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <header>
      <div class="header-container">
        <div class="logo-title-wrapper">
          <img
            src="{% static 'images/logo.png' %}"
            alt="CyberHex Logo"
            class="logo"
          />
          <div class="text-container">
            <a href="{% url 'discussion_forum:forum_index' %}">
              <h1>CyberHex</h1>
            </a>
            <p>Information sharing haven for cyber security enthusiasts.</p>
          </div>
        </div>
        <nav class="auth-menu">
          <ul>
            <form id="form" role="search">
              <input
                type="search"
                id="query"
                name="q"
                placeholder="Search..."
                aria-label="Search through site content"
              />
              <button>Search</button>
            </form>
            {% if user.is_authenticated %}
            <li>
              <a href="{% url 'user_accounts:profile' user.username %}"
                >My Profile</a
              >
            </li>
            <li>
              <a href="{% url 'user_accounts:logout' %}">Logout</a>
            </li>
            {% else %}
            <li><a href="/accounts/login">Login</a></li>
            <li><a href="/accounts/register">Register</a></li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <nav class="navbar">
        <ul>
          <li><a href="{% url 'discussion_forum:forum_index' %}">Forum</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Mission</a></li>
          <li><a href="#">CTF</a></li>
        </ul>
      </nav>
    </header>
    {% block content %} {% endblock %}
    <footer>
      <div class="footer-container">
        <p>&copy; 2024 CyberHex. All rights reserved.</p>
        <p>
          Contact us: <a href="mailto:info@cyberhex.com">info@cyberhex.com</a>
        </p>
      </div>
    </footer>
  </body>
</html>